### ISSUE TITLE
Encrypted Stream Multiplexing

### ISSUE THREAD

**Issue by TheRook** [dao-xyz/peerbit#42]
There is a unique feature in libp2p - that is encrypted multiplexing with noise:
https://github.com/libp2p/specs/blob/master/noise/README.md
https://docs.libp2p.io/concepts/multiplex/overview/

Noise has been vetted, and has been around for a while.  All other things being equal, the approach above is the most efficient way to do realtime updates as one peer with a good network connection (like a skype node) could multiplex the database update stream and/or a pub/sub event stream.

Signal and TLS + HTTP/2 do not do this.   noise + multicast appears to be a better fit for a near-realtime peerbit swarm.  If you were doing a realtime application like a video game, that still needs to be private and decentralized then I correct me if i'm wrong but I think this is currently the best solution from a performance and network traversal perspective.

**Comment by marcus-pousette** [comment]
Libp2p noise feature is something you actually have to use if you are working with browser environments. Yes, with multiplex this would be the most efficient way of doing live updates, like streaming, games etc. The tricky part is however, how to reduce overhead when you both want to have noise/stream encryption and encryption that is going to be at rest.  An additional thing I am also interested to see how WebTransport allowing TLS connections with certificate hash would  change things, 

I am working towards a live stream demo where you should be able to have many participants and have the opportunity to not only watch the stream in realtime (with noise encryption) but also rewind the stream for certain amount time if you would like (encryption at rest perhaps)  and see how that plays out in terms of performance and learn whats feasible and not from a cost/utility perspective

**Comment by TheRook** [comment]
> Libp2p noise feature is something you actually have to use if you are working with browser environments. Yes, with multiplex this would be the most efficient way of doing live updates, like streaming, games etc. The tricky part is however, how to reduce overhead when you both want to have noise/stream encryption and encryption that is going to be at rest (maybe these can these be combined for certain usecases). An additional thing I am also interested to see is how WebTransport allowing TLS connections with certificate hash would change things,
> 
> I am working towards a live stream demo where you should be able to have many participants and have the opportunity to not only watch the stream in realtime (with noise encryption) but also rewind the stream for certain amount time if you would like (encryption at rest perhaps) and see how that plays out in terms of performance and learn whats feasible and not from a cost/utility perspective

Very interesting, I'd like to see that.  It doesn't look like any games have used libp2p or Kad, maybe the existing solutions for this market work well and the distributed and censorship resistant aspect isn't really attractive to the gaming industry.  I think the TOX app is probably the largest user of Noise and they are doing live streaming of voice and video.  Tox + Multicast provides reasonable privacy for most use-cases, but it would be bad for PRISM, in that case you'd want to use I2p or Tor and then streaming wouldn't work well at all.

The streaming key and the filesystem key should be separate in all cases, you can employ a different KDF so the derived key is unique use-case and is entirely separate from a master key.   The KDF could also be used to generate the IV to prevent IV reuse - one strategy use sha512bit as a kdf and it will yield two 256bit blocks.  Encrypting the stream is a good idea and doesn't increase overhead if you aren't worried about multiplexing.
