### ISSUE TITLE
Support for query operators

### ISSUE THREAD

**Issue by threshold862543** [dao-xyz/peerbit#46]
It would be great if Peerbit supported query operators such as those used in MongoDB, such as:
 `{$in: ['abc', 'def']}`
to find documents, for example, with field values that match any of those in the array.
Here's a list of common ones:
https://www.mongodb.com/docs/manual/reference/operator/query/
(some of these already exist for FieldBigIntCompareQuery)

**Comment by marcus-pousette** [comment]
`And` and `Or` operators are now supported (@dao-xyz/peerbit-document 0.3.6) so now you can do this. 

$in is basically an Or query, 

See: 
https://github.com/dao-xyz/peerbit/blob/bb28176a74eef07fb47c5935c79b0c0726fea3ea/packages/programs/data/document/src/__tests__/index.integration.test.ts#L748
